# Determiant

Nilai determinan matriks memberikan informasi tentang apakah matriks tersebut memiliki invers (jika determinannya tidak nol), apakah matriks tersebut singuler atau tidak. Jika determinan suatu matriks adalah nol, maka matriks tersebut disebut sebagai matriks singular, yang artinya tidak memiliki invers. Sedangkan jika determinannya bukan nol, maka matriks tersebut disebut sebagai matriks nonsingular atau invertible, yang artinya memiliki invers.

## Syarat mencari determinant matrik

Hanya dapat dilakukan pada matriks bujur sangkar atau matriks persegi atau matriks yang mempunyai baris = kolom

## Sifat-sifat Determinant

Determinan dari matriks identitas = 1. Atau dapat ditulis det(I)=1

jika suatu matriks dikalikan dengan konstanta maka rumus dekterminannya:

-> constanta^berapa baris atau kolom yang dikalikan dengan konstanta(hasil determinan dari matriks asalnya)

atau

-> K^n(det(matriks asal))

keterangan :

K = konstanta

n = baris atau kolom yang telah dikalikan dengan dengan konstanta

det(matriks asal) = determinan dari matriks asal

jika matriks segitiga atas atau segitiga bawah dicari determinannya maka akan menghasilkan perkalian dari elemen di diagonalnya

det(AB) = det(A).det(B)

det(A)^2 = det(A).det(A)

det(A^T) = det(A)

In [15]:
import numpy as np

def hitung_determinan(matriks):
    det = np.linalg.det(matriks)
    return det

matriks = np.array([[4,1],[2,1]])

#A = [[1,0],[0,1]]
#B = [1,0,0],[0,1,0],[0,0,1]
#C = [1,2,1],[3,1,3],[2,1,2]
#D = [3,1,2],[1,2,1],[2,1,2]
#E = [1,2,1],[2,4,2],[2,1,2]
#F = [1,2,2],[2,4,4],[2,4,3]
#G = [6,2,4],[2,4,2],[4,2,4]
#H = [6,8],[4,2]

determinan = hitung_determinan(matriks)
print("Determinan matriks adalah:", determinan)

Determinan matriks adalah: 2.0


In [2]:
import numpy as np
def hitung_determinan(matriks):
    det = np.linalg.det(matriks)
    return det
matriks = np.array([[1,3,2],[0,0,2],[0,0,1]])
determinan = hitung_determinan(matriks)
print("Determinan matriks adalah:", determinan)

Determinan matriks adalah: 0.0


In [1]:
import numpy as np

#fungsi mencari determinan
def det(matriks):
    return np.linalg.det(matriks)

print("Membuktikan bahwa determinan dari matriks identitas adalah 1")
I=np.array([[1,0,0],[0,1,0],[0,0,1]])
print('Matriks A =\n', I)
print("determinan dari matriks i adalah",det(I))

print("perubahan baris pada matriks identitas untuk mencari determinannya")
I2=np.array([[1,0,0],[0,0,1],[0,1,0]])
print("determinan dari matriks i setelah diubah pertama kali adalah",det(I2))
I3=np.array([[0,1,0],[0,0,1],[1,0,0]])
print("determinan dari matriks i setelah diubah kedua kali adalah",det(I3),"\n")

print("mencari determinan c")
c = np.array([[1,2,1],[3,1,2],[2,1,2]])
print("determinan dari matriks c adalah",det(c).round())
d = np.array([[3,1,2],[1,2,1],[2,1,2]])
print("determinan dari matriks c setelah diubah pertama kali adalah",det(d).round())
e = np.array([[1,2,1],[2,4,2],[2,1,2]])
print("determinan dari matriks e adalah",det(e).round())
print("jika baris dikalikan dengan kelipatan maka hasilnya akan 0")
f = np.array([[1,2,1],[2,4,2],[2,4,3]])
print("determinan dari matriks f adalah",det(f).round())
g = np.array([[6,2,4],[2,4,2],[4,2,4]])
print("determinan dari matriks g adalah",det(g).round())#2^3(3)-> 2=konstanta, ^3=jumlah baris yang dikalikan dengan konstanta, (3)=hasil dari det(c)
a=np.array([[3,4],[2,1]])
print("determinan dari matriks a adalah",det(a).round())
h=np.array([[6,8],[4,2]])
print("determinan dari matriks h adalah",det(h).round()) #2^2(-5)=-20
i=np.array([[6,8],[2,1]])
print("determinan dari matriks i adalah",det(i).round()) #jika hanya satu baris saja c det(a) = 2(-5) = -10

print("\nmengalikan salah satu kolom ")
j=np.array([[6,4],[4,1]])
print("determinan dari matriks j adalah",det(j).round())#hasilnya bakal sama dengan yang salah satu baris saja yang dikalikan

Membuktikan bahwa determinan dari matriks identitas adalah 1
Matriks A =
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
determinan dari matriks i adalah 1.0
perubahan baris pada matriks identitas untuk mencari determinannya
determinan dari matriks i setelah diubah pertama kali adalah -1.0
determinan dari matriks i setelah diubah kedua kali adalah 1.0 

mencari determinan c
determinan dari matriks c adalah -3.0
determinan dari matriks c setelah diubah pertama kali adalah 3.0
determinan dari matriks e adalah 0.0
jika baris dikalikan dengan kelipatan maka hasilnya akan 0
determinan dari matriks f adalah 0.0
determinan dari matriks g adalah 24.0
determinan dari matriks a adalah -5.0
determinan dari matriks h adalah -20.0
determinan dari matriks i adalah -10.0

mengalikan salah satu kolom 
determinan dari matriks j adalah -10.0
