##Aljabar Matrik
tidak mengerjakan tidak boleh masuk

- berikan penjelasan tentang apa itu matrik
- operasi matrik
- penjumlahan, perkalian, pengurangan, transpose matrik
- buat program untuk mengalikan A dan B

"Matriks" biasanya merujuk pada kumpulan angka atau variabel yang diatur dalam bentuk tabel atau susunan. Matriks sangat umum digunakan dalam matematika, ilmu komputer, fisika, dan berbagai disiplin ilmu lainnya. Berikut adalah beberapa pengertian dan konsep dasar terkait matriks:

1. **Definisi Dasar:**
   Sebuah matriks adalah kumpulan bilangan atau variabel yang diatur dalam baris dan kolom. Sebagai contoh, sebuah matriks berukuran 2x3 (dua baris, tiga kolom) dapat terlihat seperti ini:

   
   \begin{bmatrix}
   a & b & c \\
   d & e & f \\
   \end{bmatrix}
   

   Setiap elemen matriks direpresentasikan oleh \(a\), \(b\), \(c\), \(d\), \(e\), dan \(f\).

2. **Ukuran Matriks:**
   Ukuran matriks dinyatakan dalam jumlah baris x jumlah kolom. Sebagai contoh, matriks di atas memiliki ukuran 2x3.

3. **Elemen Matriks:**
   Elemen matriks diberi label berdasarkan posisinya. Elemen pada baris ke-\(i\) dan kolom ke-\(j\) disebut \(a_{ij}\). Sebagai contoh, \(a_{23}\) merujuk pada elemen pada baris kedua dan kolom ketiga.

4. **Operasi Matriks:**
   Matriks mendukung berbagai operasi matematika, seperti penjumlahan, pengurangan, perkalian, dan invers. Operasi ini dijalankan sesuai aturan tertentu, tergantung pada jenis operasinya.

5. **Aplikasi:**
   Matriks banyak digunakan dalam pemodelan dan penyelesaian sistem persamaan linear, transformasi linier, grafika komputer, optimasi, dan berbagai bidang lainnya. Matriks juga merupakan komponen penting dalam pengolahan citra, pembelajaran mesin, dan analisis data.

Contoh operasi matriks:

- **Penjumlahan Matriks:**
  \
  \begin{bmatrix}
  a & b \\
  c & d \\
  \end{bmatrix}
  
  \begin{bmatrix}
  e & f \\
  g & h \\
  \end{bmatrix}
  
  \begin{bmatrix}
  a+e & b+f \\
  c+g & d+h \\
  \end{bmatrix}
  

- **Perkalian Matriks:**
  
  \begin{bmatrix}
  a & b \\
  c & d \\
  \end{bmatrix}
  
  \begin{bmatrix}
  e & f \\
  g & h \\
  \end{bmatrix}
  
  \begin{bmatrix}
  ae+bg & af+bh \\
  ce+dg & cf+dh \\
  \end{bmatrix}
  

Matriks memiliki peran penting dalam dunia matematika terapan dan ilmu komputer, dan konsepnya membentuk dasar bagi banyak metode dan algoritma.

Operasi matriks adalah serangkaian aturan matematis yang diterapkan pada matriks. Beberapa operasi matriks dasar melibatkan penjumlahan, pengurangan, dan perkalian. Berikut adalah penjelasan singkat tentang beberapa operasi matriks yang umum:

1. **Penjumlahan Matriks:**
   Dua matriks dapat dijumlahkan jika memiliki ukuran yang sama (jumlah baris dan kolom yang identik). Setiap elemen pada matriks hasil penjumlahan adalah hasil penjumlahan elemen-elemen yang sesuai dari dua matriks asal.

   Contoh:
   
   \begin{bmatrix}
   a & b \\
   c & d \\
   \end{bmatrix}
   +
   \begin{bmatrix}
   e & f \\
   g & h \\
   \end{bmatrix}
   =
   \begin{bmatrix}
   a+e & b+f \\
   c+g & d+h \\
   \end{bmatrix}
   

2. **Pengurangan Matriks:**
   Dua matriks dapat dikurangkan jika memiliki ukuran yang sama. Setiap elemen pada matriks hasil pengurangan adalah hasil pengurangan elemen-elemen yang sesuai dari dua matriks asal.

   Contoh:
   
   \begin{bmatrix}
   a & b \\
   c & d \\
   \end{bmatrix}
   -
   \begin{bmatrix}
   e & f \\
   g & h \\
   \end{bmatrix}
   =
   \begin{bmatrix}
   a-e & b-f \\
   c-g & d-h \\
   \end{bmatrix}
   

3. **Perkalian Skalar:**
   Matriks dapat dikalikan dengan skalar (sebuah bilangan). Setiap elemen pada matriks dikalikan dengan skalar tersebut.

   Contoh:
   
   k \times
   \begin{bmatrix}
   a & b \\
   c & d \\
   \end{bmatrix}
   =
   \begin{bmatrix}
   ka & kb \\
   kc & kd \\
   \end{bmatrix}
   

4. **Perkalian Matriks:**
   Perkalian matriks melibatkan kombinasi elemen-elemen dari dua matriks untuk menghasilkan matriks baru. Aturan perkalian matriks adalah bahwa jumlah kolom matriks pertama harus sama dengan jumlah baris matriks kedua.

   Contoh:
   
   \begin{bmatrix}
   a & b \\
   c & d \\
   \end{bmatrix}
   \times
   \begin{bmatrix}
   e & f \\
   g & h \\
   \end{bmatrix}
   =
   \begin{bmatrix}
   ae+bg & af+bh \\
   ce+dg & cf+dh \\
   \end{bmatrix}
   

5. **Transpos Matriks:**
   Transpos matriks menghasilkan matriks baru dengan menukar baris dan kolom. Jika \(A\) adalah matriks, transpos \(A^T\) memiliki elemen-elemen yang disusun ulang, yaitu \(a_{ij}^T = a_{ji}\).

   Contoh:
   
   \text{Jika } A =
   \begin{bmatrix}
   a & b \\
   c & d \\
   \end{bmatrix}
   \text{, maka } A^T =
   \begin{bmatrix}
   a & c \\
   b & d \\
   \end{bmatrix}
   

Operasi matriks ini sangat penting dalam berbagai bidang seperti matematika, ilmu komputer, fisika, dan rekayasa.

In [ ]:
import numpy as np
import sympy as sy

In [ ]:
import numpy as np
A = np.array([[1, 3, 3],[2, 1, 9],[2, 4, 7]])
B = np.array([[1,6,3],[2,8,7],[3,9,5]]) #3x3
C = np.array([[2,4],[5,2],[6,7]]) #3x2
D = np.array([[3,7,5],[1,4,8],[2,4,5]])
E = A+B
F = 2*A #Skala
G = A@C #perkalian
H = B@C
I = A@H
J = A@B
K = J@C
L = A-B

C_trans = C.transpose()
Z = C_trans@C
print(E)
print('\n')
print(F)
print('\n')
print(G)
print('\n')
print(I)
print('\n')
print(K)
print('\n')
print(L)
print('\n')
print(C_trans)
print(Z)
print('\n')
print(J)

[[ 2  9  6]
 [ 4  9 16]
 [ 5 13 12]]


[[ 2  6  6]
 [ 4  2 18]
 [ 4  8 14]]


[[35 31]
 [63 73]
 [66 65]]


[[ 551  451]
 [ 915  732]
 [1011  821]]


[[ 551  451]
 [ 915  732]
 [1011  821]]


[[ 0 -3  0]
 [ 0 -7  2]
 [-1 -5  2]]


[[2 5 6]
 [4 2 7]]
[[65 60]
 [60 69]]


[[ 16  57  39]
 [ 31 101  58]
 [ 31 107  69]]


In [ ]:
def matrix_multiplication(A, B):
    result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]

    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]

    return result

hasil = matrix_multiplication(A, B)

for row in hasil:
    print(row)


[16, 57, 39]
[31, 101, 58]
[31, 107, 69]
