# UAS KOMPUTASI ALJABAR LINEAR

## 1.	Hitunglah PageRank dari graph berikut

In [6]:
import networkx as nx

# Fungsi untuk menghitung PageRank
def hitung_pagerank():
    G = nx.DiGraph()

    # Menambahkan edges sesuai dengan gambar graf
    edges = [(1, 2), (2, 3), (3, 1), (3, 5), (4, 1), (4, 5), (5, 4), (5, 2)]
    G.add_edges_from(edges)

    # Menghitung PageRank
    pagerank = nx.pagerank(G, alpha=0.85)

    return pagerank

# Menyelesaikan perhitungan PageRank
pagerank_hasil = hitung_pagerank()

# Menampilkan hasil
print("Hasil PageRank:")
for node, rank in pagerank_hasil.items():
    print(f"Node {node}: {rank:.4f}")

Hasil PageRank:
Node 1: 0.1849
Node 2: 0.2657
Node 3: 0.2559
Node 5: 0.1849
Node 4: 0.1086


In [7]:
import networkx as nx
# Buat grafik
G = nx.Graph()
G.add_nodes_from(['A', 'B', 'C', 'D', 'E'])
G.add_edges_from([('A', 'B'), ('A', 'C'), ('B', 'D'), ('B', 'E'), ('C', 'D'), ('C', 'E'), ('D', 'E')])
# Hitung PageRank
pr = nx.pagerank(G, alpha=0.85)
# Cetak hasil
print(pr)


{'A': 0.15107497101269424, 'B': 0.21366050844932935, 'C': 0.21366050844932935, 'D': 0.2108020060443234, 'E': 0.2108020060443234}


## 2. Carilah penyelesaian dari Sistem persamaan berikut dengan Eliminasi Gauss
 $x_{1}-x_{2}+x_{3}=3$

 $2x_{1}+x_{2}+3x_{3}=8$

 $6x_{1}-x_{3}=4$


In [3]:
import numpy as np

# Matriks augmented
A = np.array([[1, -1, 1, 3],
              [2, 1, 3, 8],
              [6, 0, -1, 4]], dtype=float)

# Matriks untuk menyimpan hasil
E = np.copy(A)

# Loop untuk mereduksi matriks E ke bentuk eselon baris
for i in range(3):
    # Temukan baris pivot
    baris_pivot = i
    for j in range(i+1, 3):
        if np.abs(E[j, i]) > np.abs(E[baris_pivot, i]):
            baris_pivot = j
    # Tukar baris pivot dengan baris saat ini
    E[[i, baris_pivot]] = E[[baris_pivot, i]]

    # Normalisasi baris pivot
    E[i] = E[i] / E[i, i]

    # Eliminasi baris di bawah
    for j in range(i+1, 3):
        E[j] = E[j] - E[j, i] * E[i]

# Loop untuk mereduksi matriks E ke bentuk eselon baris tereduksi
for i in range(2, -1, -1):
    for j in range(i-1, -1, -1):
        E[j] = E[j] - E[j, i] * E[i]

# Matriks solusi
X = np.copy(E)

print("Bentuk eselon baris tereduksi dari matriks augmented adalah:")
print(X)

# Ekstrak solusi
solusi = X[:, -1]
print("Solusi: ", solusi)

Bentuk eselon baris tereduksi dari matriks augmented adalah:
[[1. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 2.]]
Solusi:  [1. 0. 2.]


In [5]:
import numpy as np

def eliminasi_gauss(A, b):
    n = len(b)

    for i in range(n):
        # Normalisasi baris i
        faktor = A[i][i]
        for j in range(i, n):
            A[i][j] /= faktor
        b[i] /= faktor

        # Eliminasi baris di bawah baris i
        for k in range(i + 1, n):
            faktor = A[k][i]
            for j in range(i, n):
                A[k][j] -= faktor * A[i][j]
            b[k] -= faktor * b[i]

    # Back substitution
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = b[i] - sum(A[i][j] * x[j] for j in range(i + 1, n))

    return x

# Definisikan sistem persamaan sebagai matriks
A = np.array([[1, -1, 1], [2, 1, 3], [6, 0, -1]], dtype=float)
b = np.array([3, 8, 4], dtype=float)

# Panggil fungsi eliminasi Gauss
eliminasi_gauss_hasil = eliminasi_gauss(A, b)

# Cetak solusi
print("Hasil Eliminasi Gauss:")
for i, value in enumerate(eliminasi_gauss_hasil, 1):
    print(f"x{i} = {value:.4f}")


Hasil Eliminasi Gauss:
x1 = 1.0000
x2 = 0.0000
x3 = 2.0000
